

class BoardComponent {

    public static String images[] = {
        "go.jpg",
        "oldkent.jpg",
        "community.jpg",
        "whitechapel.jpg",
        "income.jpg",
        "kingscross.jpg",
        "angel.jpg",
        "chance_pink.jpg",
        "euston.jpg",
        "pentonville.jpg",
        "in_jail.jpg",
        "pallmall.jpg",
        "electric.jpg",
        "whitehall.jpg",
        "northumberland.jpg",
        "marylebone.jpg",
        "bow.jpg",
        "community1.jpg",
        "marlborough.jpg",
        "vine.jpg",
        "freeparking.jpg",
        "strand.jpg",
        "chance_blue.jpg",
        "fleet.jpg",
        "trafalgar.jpg",
        "fenchurch.jpg",
        "leicester.jpg",
        "coventry.jpg",
        "waterworks.jpg",
        "piccadilly.jpg",
        "goto_jail.jpg",
        "regent.jpg",
        "oxford.jpg",
        "community2.jpg",
        "bond.jpg",
        "liverpool.jpg",
        "chance_orange.jpg",
        "parklane.jpg",
        "super.jpg",
        "mayfair.jpg"
    };
    public static String Deeds[] = {
        "go.jpg",
        "oldkent.png",
        "community.png",
        "whitechapel.png",
        "tax.png",
        "kingscross.png",
        "angel.png",
        "chance.png",
        "euston.png",
        "pentonville.png",
        "in_jail.png",
        "pallmall.png",
        "electric.png",
        "whitehall.png",
        "northumberland.png",
        "marylebone.png",
        "bow.png",
        "community.png",
        "marlborough.png",
        "vine.png",
        "freeparking.png",
        "strand.png",
        "chance.png",
        "fleet.png",
        "trafalgar.png",
        "fenchurch.png",
        "leicester.png",
        "coventry.png",
        "waterworks.png",
        "piccadilly.png",
        "goto_jail.png",
        "regent.png",
        "oxford.png",
        "community.png",
        "bond.png",
        "liverpool.png",
        "chance.png",
        "parklane.png",
        "tax.png",
        "mayfair.png"
    };
    public static String own[] = {
        "oldkent.png",
        "whitechapel.png",
        "",
        "angel.png",
        "euston.png",
        "pentonville.png",
        "pallmall.png",
        "whitehall.png",
        "northumberland.png",
        "bow.png",
        "marlborough.png",
        "vine.png",
        "strand.png",
        "fleet.png",
        "trafalgar.png",
        "leicester.png",
        "coventry.png",
        "piccadilly.png",
        "regent.png",
        "oxford.png",
        "bond.png",
        "parklane.png",
        "mayfair.png",
        "",
        "kingscross.png",
        "marylebone.png",
        "fenchurch.png",
        "liverpool.png",
        "electric.png",
        "waterworks.png",
    };
    public static int position[][] = {
        {820, 820, 100, 100},
        {720, 820, 100, 100},
        {620, 820, 100, 100},
        {520, 820, 100, 100},
    };
    public static int pos[] = {820, 820, 100, 100};

    public BoardComponent() {
    }
}